### ISSUE TITLE
Twilight Forest Integration?

### ISSUE THREAD

**Issue by PechayClub** [TeamBurnuts/BurnutsPlusTNTandDisparityMod#1]
Have Twilight Forest Integration in this mod using the maven.

**Comment by Azar2477** [comment]
Were having problem compiling because of a Gradle version mismatch.
Our Gradle version is 6.9 while the one in Twilight Forest is 4.9.

**Comment by Burnuts** [comment]
I found an issue that can hinder the TNT and Disparity progression.
https://github.com/TeamTwilight/twilightforest/issues/718

**Comment by Azar2477** [comment]
Yup. It's because the generation is glitched and you wont get to go to the Carminite Tower to finish the mod.

**Comment by Burnuts** [comment]
I hope it gets fixed soon.

**Comment by Pechayland** [comment]
Yup I saw that pinned issue.
So we need to create something in TNT and Disparity mod to fix it or I can create a code that will fix this which is hard because you need to modify the generation but I will check the older codes.

**Comment by Pechayland** [comment]
There is no Gradle wrapper in branch 1.7.10 which means I don't know what Gradle version is it compiled in.

**Comment by Azar2477** [comment]
Gradle is updated to 7.1.1.

**Comment by Azar2477** [comment]
They update their Gradle to 7.2.

**Comment by Pechayland** [comment]
Ok

**Comment by Burnuts** [comment]
It will take place in 1.17.1.

**Comment by Pechayland** [comment]
Permission is needed first before Integration Test because we will copy the code to our mod.

**Comment by Azar2477** [comment]
I'm reassigned.
I will try to help develop Twilight Forest Dependencies API Plugin version 1.3.

**Comment by Burnuts** [comment]
> I'm reassigned. I will try to help develop Twilight Forest Dependencies API Plugin version 1.3.

You did not update the Plugin for Twilight Forest 1.17

**Comment by Burnuts** [comment]
I don't know if we can close this. @aaronschneider7797

**Comment by aaronschneider7797** [comment]
Not so soon. I'm fixing the bugs on the Integration Mod.

**Comment by Burnuts** [comment]
Is it complete? @aaronschneider7797

**Comment by aaronschneider7797** [comment]
> Is it complete? @aaronschneider7797

Not yet. We did not finish Integration Test. We have 2 more to pass. (0.5 and 0.6)
