### ISSUE TITLE
1.12.2 Backport

### ISSUE THREAD

**Issue by ForceerGames** [TeamBurnuts/BurnutsPlusTNTandDisparityMod#19]
**Is your feature request related to a problem? Please describe.**
I played Minecraft 1.12.2 and there is a maven for TF 1.12 and 1.15.

**Describe the solution you'd like**
Port the mod to 1.12 for me because most of the mods are in 1.12.2.

**Describe alternatives you've considered**
Thats the only one I want.

**Comment by Burnuts** [comment]
Sorry, @ForceerGames we don't support legacy MCP Minecraft versions anymore

**Comment by Pechayland** [comment]
:wave: @ForceerGames, we don't support the corsponding Minecraft or mod version anymore. You can fix this yourself by third-party/unofficial maintainment from a forked Github branch. Go to [SECURITY.md](https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/blob/master/SECURITY.md) for more info.

**Comment by BurnutsGaming** [comment]
The maven for that is now offline. Use CurseMaven instead for it. (No 1.15)
